### ISSUE TITLE
Some weird shit is happening right there

### ISSUE THREAD

**Issue by wswld** [wswld/menage#79]
```
Creating test database for alias 'default'...
E
======================================================================
ERROR: Failure: RuntimeError (Conflicting 'customuser_groups' models in application 'core': <class 'core.models.CustomUser_groups'> and <class 'menage.core.models.CustomUser_groups'>.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose-1.3.3-py2.7.egg/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/wswld/Code/menage/core/tests.py", line 2, in <module>
    from models import UUIDModel
  File "/home/wswld/Code/menage/core/models.py", line 28, in <module>
    class CustomUser(AbstractUser):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 253, in __new__
    new_class.add_to_class(field.name, copy.deepcopy(field))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 300, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 2231, in contribute_to_class
    self.rel.through = create_many_to_many_intermediary_model(self, cls)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1841, in create_many_to_many_intermediary_model
    to: models.ForeignKey(to_model, related_name='%s+' % name, db_tablespace=field.db_tablespace, db_constraint=field.rel.db_constraint)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 286, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 201, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'customuser_groups' models in application 'core': <class 'core.models.CustomUser_groups'> and <class 'menage.core.models.CustomUser_groups'>.
-------------------- >> begin captured logging << --------------------
django.db.backends.schema: DEBUG: CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "django_content_type__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL, UNIQUE ("app_label", "model")); (params [])
django.db.backends.schema: DEBUG: INSERT INTO "django_content_type__new" ("model", "app_label", "id", "name") SELECT "model", "app_label", "id", "name" FROM "django_content_type"; (params [])
django.db.backends.schema: DEBUG: DROP TABLE "django_content_type"; (params [])
django.db.backends.schema: DEBUG: ALTER TABLE "django_content_type__new" RENAME TO "django_content_type"; (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "codename" varchar(100) NOT NULL, UNIQUE ("content_type_id", "codename")); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"), UNIQUE ("group_id", "permission_id")); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX auth_permission_417f1b1c ON "auth_permission" ("content_type_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX auth_group_permissions_0e939a4f ON "auth_group_permissions" ("group_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX auth_group_permissions_8373b171 ON "auth_group_permissions" ("permission_id"); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_customuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NOT NULL, "is_superuser" bool NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "theme" varchar(22) NOT NULL, "description" text NULL); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_customuser_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" integer NOT NULL REFERENCES "core_customuser" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), UNIQUE ("customuser_id", "group_id")); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_customuser_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" integer NOT NULL REFERENCES "core_customuser" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"), UNIQUE ("customuser_id", "permission_id")); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_uuidmodel" ("uuid" varchar(22) NOT NULL PRIMARY KEY); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_subcategory" ("uuidmodel_ptr_id" varchar(22) NOT NULL PRIMARY KEY REFERENCES "core_uuidmodel" ("uuid"), "name" varchar(25) NOT NULL UNIQUE, "description" text NULL); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_entry" ("uuidmodel_ptr_id" varchar(22) NOT NULL PRIMARY KEY REFERENCES "core_uuidmodel" ("uuid"), "value" decimal NOT NULL, "date" date NOT NULL, "description" text NULL, "subcategory_id" varchar(22) NOT NULL REFERENCES "core_subcategory" ("uuidmodel_ptr_id"), "issuer_id" integer NOT NULL REFERENCES "core_customuser" ("id")); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_category" ("uuidmodel_ptr_id" varchar(22) NOT NULL PRIMARY KEY REFERENCES "core_uuidmodel" ("uuid"), "name" varchar(25) NOT NULL UNIQUE, "description" text NULL); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_subcategory__new" ("uuidmodel_ptr_id" varchar(22) NOT NULL PRIMARY KEY REFERENCES "core_uuidmodel" ("uuid"), "name" varchar(25) NOT NULL UNIQUE, "description" text NULL, "parent_id" varchar(22) NOT NULL REFERENCES "core_category" ("uuidmodel_ptr_id")); (params [])
django.db.backends.schema: DEBUG: INSERT INTO "core_subcategory__new" ("description", "uuidmodel_ptr_id", "name") SELECT "description", "uuidmodel_ptr_id", "name" FROM "core_subcategory"; (params [])
django.db.backends.schema: DEBUG: DROP TABLE "core_subcategory"; (params [])
django.db.backends.schema: DEBUG: ALTER TABLE "core_subcategory__new" RENAME TO "core_subcategory"; (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_customuser_groups_721e74b0 ON "core_customuser_groups" ("customuser_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_customuser_groups_0e939a4f ON "core_customuser_groups" ("group_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_customuser_user_permissions_721e74b0 ON "core_customuser_user_permissions" ("customuser_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_customuser_user_permissions_8373b171 ON "core_customuser_user_permissions" ("permission_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_entry_79f70305 ON "core_entry" ("subcategory_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_entry_dff64d5b ON "core_entry" ("issuer_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_subcategory_6be37982 ON "core_subcategory" ("parent_id"); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_account" ("uuidmodel_ptr_id" varchar(22) NOT NULL PRIMARY KEY REFERENCES "core_uuidmodel" ("uuid"), "name" varchar(4) NOT NULL UNIQUE, "description" text NULL, "owner_id" integer NOT NULL REFERENCES "core_customuser" ("id")); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_entry__new" ("uuidmodel_ptr_id" varchar(22) NOT NULL PRIMARY KEY REFERENCES "core_uuidmodel" ("uuid"), "value" decimal NOT NULL, "date" date NOT NULL, "description" text NULL, "subcategory_id" varchar(22) NOT NULL REFERENCES "core_subcategory" ("uuidmodel_ptr_id"), "issuer_id" integer NOT NULL REFERENCES "core_customuser" ("id"), "account_id" varchar(22) NOT NULL REFERENCES "core_account" ("uuidmodel_ptr_id")); (params [])
django.db.backends.schema: DEBUG: INSERT INTO "core_entry__new" ("description", "subcategory_id", "uuidmodel_ptr_id", "value", "issuer_id", "date") SELECT "description", "subcategory_id", "uuidmodel_ptr_id", "value", "issuer_id", "date" FROM "core_entry"; (params [])
django.db.backends.schema: DEBUG: DROP TABLE "core_entry"; (params [])
django.db.backends.schema: DEBUG: ALTER TABLE "core_entry__new" RENAME TO "core_entry"; (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_account_5e7b1936 ON "core_account" ("owner_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_entry_79f70305 ON "core_entry" ("subcategory_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_entry_dff64d5b ON "core_entry" ("issuer_id"); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX core_entry_8a089c2a ON "core_entry" ("account_id"); (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "core_customuser__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NOT NULL, "is_superuser" bool NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "description" text NULL, "theme" varchar(22) NOT NULL); (params [])
django.db.backends.schema: DEBUG: INSERT INTO "core_customuser__new" ("username", "first_name", "last_name", "description", "is_active", "email", "is_superuser", "theme", "is_staff", "last_login", "password", "id", "date_joined") SELECT "username", "first_name", "last_name", "description", "is_active", "email", "is_superuser", "theme", "is_staff", "last_login", "password", "id", "date_joined" FROM "core_customuser"; (params [])
django.db.backends.schema: DEBUG: DROP TABLE "core_customuser"; (params [])
django.db.backends.schema: DEBUG: ALTER TABLE "core_customuser__new" RENAME TO "core_customuser"; (params [])
django.db.backends.schema: DEBUG: CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL); (params [])
django.db.backends.schema: DEBUG: CREATE INDEX django_session_de54fa62 ON "django_session" ("expire_date"); (params [])
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.001s
```

**Comment by wswld** [comment]
Yay!
